spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: skdisk17
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update